kind: pipeline
name: default

steps:
- name: build
  image: ruby
  pull: true
  commands:
  - gem install bundler
  - bundle install
  - JEKYLL_ENV=production bundle exec jekyll build
- name: deploy
  image: drillster/drone-rsync
  settings:
    hosts: [ "rick.kerjean.me" ]
    source: _site/*
    target: /mnt/app-filestash-www/
    recursive: true
    delete: true
    user:
      from_secret: RSYNC_USER
    key:
      from_secret: RSYNC_KEY
